name: cornelius
favicon: null
layout_spectrum: 0.4505796409212053
typography_spectrum: 0.5968709646258503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5994476263877004
  lightness: 0.761470063822344
  saturation: 0.31384672108106315
  rhythmicContrast: 0.06132123409770429
purpose: []
